name: flutter_example
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  file_picker: ^5.3.2
  csv: ^5.0.2 # Add the CSV package dependency
  path_provider: ^2.0.15
  excel: ^2.1.0
  shared_preferences: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_application_1: ^0.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
